import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Button from "../componets/Button";
export default function Home() {
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Frontend Mentor | Meet landing page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/image/favicon-32x32.png" />
            </Head>
            <div className={styles.header} role="banner">
                <img src="/image/logo.svg" alt="logo" />
            </div>
            <div className={styles.main} role="main">
                <img src="/image/tablet/image-hero.png" alt="" />
                <div className={styles.main_info}>
                    <h1>Group Chat for Everyone</h1>
                    <p>
                        Meet makes it easy to connect with others face-to-face
                        virtually and collaborate across any device.
                    </p>
                    <div className={styles.wrap_btn}>
                        <Button
                            title="Download"
                            color="blue"
                            version="v1.3"
                            vcolor="lightblue"
                        />
                        <Button title="What is it?" />
                    </div>
                </div>
            </div>
            <div className={styles.number_container}>
                <div className={styles.line}></div>
                <div className={styles.number}>
                    <p>01</p>
                </div>
            </div>
            <div className={styles.img_container}>
                <img src="/image/desktop/image-woman-in-videocall.jpg" alt="" />

                <img
                    src="/image/desktop/image-women-videochatting.jpg"
                    alt=""
                />

                <img src="/image/desktop/image-men-in-meeting.jpg" alt="" />

                <img src="/image/desktop/image-man-texting.jpg" alt="" />
            </div>
            <div className={styles.section_info}>
                <p className={styles.blu_txt}> BUILT FOR MODERN USE</p>
                <h2> Smarter meetings, all in one place</h2>
                <p>
                    Send messages, share files, show your screen, and record
                    your meetings — all in one workspace. Control who can join
                    with invite-only team access, data encryption, and data
                    export.
                </p>
            </div>
            <div className={`${styles.number_container} ${styles.position}`}>
                <div className={styles.line}></div>
                <div className={styles.number}>
                    <p>02</p>
                </div>
            </div>
            <div className={styles.footer} role="contentinfo">
                <div className={styles.footer_container}>
                    <h2> Experience more together</h2>
                    <p>
                        Stay connected with reliable HD meetings and unlimited
                        one-on-one and group video sessions.
                    </p>
                    <Button
                        title="What is it?"
                        version="v1.3"
                        vcolor="violet"
                    />
                </div>
            </div>
        </div>
    );
}
